spring:
  # enable h2 console
  h2:
    console:
      enabled: true
      path: /h2-console
  # database source
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  # disable test db replace
  test:
    database:
      replace: none

# log config
logging:
  level:
    # enable hibernate sql parameter log
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE
